resource "tls_private_key" "ssh_key" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "aws_key_pair" "generated_key" {
  key_name   = "key-${var.environment}-${var.region}-${var.instance_name}"
  public_key = tls_private_key.ssh_key.public_key_openssh
}

variable "ssh_user" {
  description = "User to connect via SSH"
  type        = string
}


resource "aws_instance" "debian_instance" {
  ami                         = var.ami
  instance_type               = var.instance_type
  key_name                    = aws_key_pair.generated_key.key_name
  vpc_security_group_ids      = [aws_security_group.instance_sg.id]
  subnet_id                   = var.subnet_id != "" ? var.subnet_id : null
  associate_public_ip_address = var.enable_public_ip

  tags = {
    Environment = var.environment
    Region      = var.region
    Name        = "${var.environment}-${var.instance_name}-app"
    Role        = "medusa-app"
  }

  # Note: Ansible provisioning is handled via the inventory generated by Terraform
  # No remote-exec provisioner needed - Ansible will connect directly
}

# Enregistrer l'instance dans le Target Group de l'ALB
resource "aws_lb_target_group_attachment" "app" {
  target_group_arn = var.alb_target_group_arn
  target_id        = aws_instance.debian_instance.id
  port             = 9000  # Port du backend Medusa
}

resource "local_file" "ssh_private_key" {
  content  = tls_private_key.ssh_key.private_key_pem
  filename = "${path.root}/keys/${var.environment}-${var.region}-${var.instance_name}-key.pem"
  file_permission = "0400"
}