---
# ===========================================
# Ansible Inventory - Generated by Terraform
# Multi-Region Architecture with ALB
# ===========================================

all:
  vars:
    ansible_user: ${ssh_user}
    ansible_python_interpreter: /usr/bin/python3

    # Database configuration (dynamically generated)
    database_url: "postgres://medusa:medusa_secure_password_change_me@${france_db_primary_public_ip}:5432/medusa"

  children:
    # ========================================
    # FRANCE REGION
    # ========================================
    france:
      children:
        france_app:
          hosts:
            france-prod-app-1:
              ansible_host: ${france_app_1_public_ip}
              private_ip: ${france_app_1_private_ip}
              ansible_ssh_private_key_file: ${keys_path}/prod-${france_aws_region}-app-1-key.pem
              env_name: prod
              region: france
              role: medusa-app

            france-prod-app-2:
              ansible_host: ${france_app_2_public_ip}
              private_ip: ${france_app_2_private_ip}
              ansible_ssh_private_key_file: ${keys_path}/prod-${france_aws_region}-app-2-key.pem
              env_name: prod
              region: france
              role: medusa-app

        france_database:
          hosts:
            france-prod-db-primary:
              ansible_host: ${france_db_primary_public_ip}
              private_ip: ${france_db_primary_private_ip}
              ansible_ssh_private_key_file: ${keys_path}/prod-france-db-key.pem
              env_name: prod
              region: france
              role: database-primary
              db_type: primary

%{ for idx, ip in france_db_replica_public_ips ~}
            france-prod-db-replica-${idx + 1}:
              ansible_host: ${ip}
              private_ip: ${france_db_replica_private_ips[idx]}
              ansible_ssh_private_key_file: ${keys_path}/prod-france-replica-db-key.pem
              env_name: prod
              region: france
              role: database-replica
              db_type: replica
              primary_db_ip: ${france_db_primary_private_ip}

%{ endfor ~}

    # ========================================
    # GERMANY REGION
    # ========================================
    germany:
      children:
        germany_app:
          hosts:
            germany-prod-app-1:
              ansible_host: ${germany_app_1_public_ip}
              private_ip: ${germany_app_1_private_ip}
              ansible_ssh_private_key_file: ${keys_path}/prod-${germany_aws_region}-app-1-key.pem
              env_name: prod
              region: germany
              role: medusa-app

            germany-prod-app-2:
              ansible_host: ${germany_app_2_public_ip}
              private_ip: ${germany_app_2_private_ip}
              ansible_ssh_private_key_file: ${keys_path}/prod-${germany_aws_region}-app-2-key.pem
              env_name: prod
              region: germany
              role: medusa-app

        germany_database:
          hosts:
%{ for idx, ip in germany_db_replica_public_ips ~}
            germany-prod-db-replica-${idx + 1}:
              ansible_host: ${ip}
              private_ip: ${germany_db_replica_private_ips[idx]}
              ansible_ssh_private_key_file: ${keys_path}/prod-germany-db-key.pem
              env_name: prod
              region: germany
              role: database-replica
              db_type: replica
              primary_db_ip: ${france_db_primary_public_ip}

%{ endfor ~}

    # ========================================
    # ROLE GROUPS
    # ========================================
    medusa_app:
      children:
        france_app:
        germany_app:

    databases:
      children:
        france_database:
        germany_database:

    database_primary:
      hosts:
        france-prod-db-primary:

    database_replicas:
      hosts:
%{ for idx, ip in france_db_replica_private_ips ~}
        france-prod-db-replica-${idx + 1}:
%{ endfor ~}
%{ for idx, ip in germany_db_replica_private_ips ~}
        germany-prod-db-replica-${idx + 1}:
%{ endfor ~}
