apiVersion: v1
kind: Secret
metadata:
  name: medusa-secrets
  namespace: medusa
type: Opaque
stringData:
  DATABASE_PASSWORD: "Medusa_DB_2024!"
  JWT_SECRET: "medusa-jwt-secret-greenleaf-2024-secure"
  COOKIE_SECRET: "medusa-cookie-secret-greenleaf-2024"
  ADMIN_PASSWORD: "Admin1234!"
