apiVersion: apps/v1
kind: Deployment
metadata:
  name: medusa-storefront
  namespace: medusa
  labels:
    app: medusa-storefront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medusa-storefront
  template:
    metadata:
      labels:
        app: medusa-storefront
    spec:
      containers:
        - name: medusa-storefront
          image: 622333992348.dkr.ecr.eu-west-3.amazonaws.com/jugurta-dev-prod-medusa-storefront:latest
          ports:
            - containerPort: 8000
          env:
            - name: NEXT_PUBLIC_MEDUSA_BACKEND_URL
              value: "http://medusa-backend"
            - name: MEDUSA_BACKEND_URL
              value: "http://medusa-backend"
            - name: NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY
              value: "pk_ad0dc48858f95ad65eae03d9873407acafa02c800ee5ca3f2a8b1c66a0335a27"
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              memory: "256Mi"
              cpu: "125m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /favicon.ico
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /favicon.ico
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
